### ISSUE TITLE
Read documents from database

### ISSUE THREAD

**Issue by sid-dinesh94** [ailab-uniud/distiller-CORE#16]
I would like to read documents for analyzing for keyphrases from a database directly, instead of files. 
Can someone please point me to which files I can look at editing to add this option?
I can do the development of the code for this purpose.

**Comment by basaldella** [comment]
Hello, 

I think a good idea would be to set up your own launcher that loads the data you need from the blackboard and then instantiates its own pipeline. Have a look at the [simplest launcher](https://github.com/ailab-uniud/distiller-CORE/blob/master/src/main/java/it/uniud/ailab/dcore/launchers/SimpleKE.java): that's the basic skeleton, you can just modify it to your needs.
